Análisis de componentes principales

In [1]:
import pandas as pd
import numpy as np


In [2]:
base = pd.read_csv(".\\AumentadaPFLD.csv")  #leer la base

In [6]:
matriz = base.to_numpy()

In [8]:
Matriz_covarianza = np.cov(matriz)
Matriz_covarianza

array([[141.92643678,  99.65517241,  78.89655172, ...,   6.04137931,
          1.35862069,  16.1862069 ],
       [ 99.65517241, 107.5862069 ,  60.79310345, ...,  -1.17241379,
          8.79310345,  10.62068966],
       [ 78.89655172,  60.79310345, 108.67241379, ...,  19.01724138,
         -4.51724138,  17.03448276],
       ...,
       [  6.04137931,  -1.17241379,  19.01724138, ...,  92.64482759,
         50.49655172,  53.6       ],
       [  1.35862069,   8.79310345,  -4.51724138, ...,  50.49655172,
         60.30344828,  43.57931034],
       [ 16.1862069 ,  10.62068966,  17.03448276, ...,  53.6       ,
         43.57931034,  92.92413793]])

In [9]:
from scipy import stats
matriz_estandarizada = stats.zscore(matriz, axis=1)


In [10]:
Matriz_correlacion = np.cov(matriz_estandarizada)
Matriz_correlacion

array([[ 1.03448276,  0.83428254,  0.65718853, ...,  0.05450259,
         0.01519213,  0.145805  ],
       [ 0.83428254,  1.03448276,  0.58162038, ..., -0.01214829,
         0.11293175,  0.10988373],
       [ 0.65718853,  0.58162038,  1.03448276, ...,  0.19606521,
        -0.05772525,  0.17535909],
       ...,
       [ 0.05450259, -0.01214829,  0.19606521, ...,  1.03448276,
         0.69888113,  0.59760358],
       [ 0.01519213,  0.11293175, -0.05772525, ...,  0.69888113,
         1.03448276,  0.60223815],
       [ 0.145805  ,  0.10988373,  0.17535909, ...,  0.59760358,
         0.60223815,  1.03448276]])

In [26]:
Matriz_covarianza

array([[141.93, 99.66, 78.90, ..., 6.04, 1.36, 16.19],
       [99.66, 107.59, 60.79, ..., -1.17, 8.79, 10.62],
       [78.90, 60.79, 108.67, ..., 19.02, -4.52, 17.03],
       ...,
       [6.04, -1.17, 19.02, ..., 92.64, 50.50, 53.60],
       [1.36, 8.79, -4.52, ..., 50.50, 60.30, 43.58],
       [16.19, 10.62, 17.03, ..., 53.60, 43.58, 92.92]])

In [13]:
import numpy as np
from numpy.linalg import eig

In [15]:
v = eig(Matriz_covarianza)

In [28]:
 float_formatter = "{:.2f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})
r = v[0]

In [31]:
r[0]


(1.418996322848e-311+1.419158527872e-311j)