Análisis de componentes principales

In [24]:
import pandas as pd
import numpy as np


In [6]:
base = pd.read_csv(".\\AumentadaPFLD.csv")  #leer la base

In [52]:
Covarianza = base.cov().to_numpy()#matriz de covarianza
Correlacion = base.corr()#matriz de correlación

In [59]:
Covarianza

array([[ 635.68188347,  656.47619971,  464.62303775,  667.57803846,
         407.46947903,  562.1382119 ,  717.12910752,  502.88613813,
         365.55756443,  497.09551181,  528.25162037,  583.50428733,
         534.28356106,  539.17059781,  638.20387856,  442.29643334,
         396.3704974 ,  350.32943251,  397.05064835,  395.61788428,
         429.17310635,  396.56075298,  435.39937382,  501.78926031,
         440.33205959,  415.78560918,  488.69976998,  698.6055117 ,
         769.30460002,  633.65563467],
       [ 656.47619971, 1210.78939658,  577.88314794,  890.52035944,
         549.21395944,  668.04751738, 1033.67571565,  552.83791213,
         492.79792519,  572.95061973,  659.01182333,  659.82447641,
         617.63255634,  597.52865072,  698.98636316,  806.03039632,
         505.38724892,  390.2241856 ,  399.8702055 ,  455.52188932,
         497.37291567,  383.68348046,  439.86875024,  483.40202765,
         432.97714318,  469.09464085,  536.52155173,  650.35060818,
         

In [60]:
scale_base = (base - base.mean())/base.std() #base de datos escalada, la matriz de covarianza de los datos escalados es igual a la matriz de correlación de elos datos normales

In [64]:
Corr1 = scale_base.cov() #covarianza sobre los datos escalados
Corr2 = Correlacion = base.corr()#matriz de correlación


In [66]:
eigen_values_vectos = np.linalg.eig(Corr1)

In [74]:
Eigenvalores = eigen_values_vectos[0]
for eigenvalor in Eigenvalores:
    print(round(eigenvalor,2))

23.03
1.74
1.0
0.69
0.49
0.45
0.29
0.22
0.21
0.01
0.02
0.02
0.03
0.03
0.04
0.05
0.06
0.07
0.08
0.08
0.09
0.18
0.17
0.16
0.16
0.11
0.15
0.12
0.13
0.13


In [75]:
Eigengectores = eigen_values_vectos[1]
Eigenvectores

array([2.30343264e+01, 1.73881986e+00, 1.00192107e+00, 6.85168016e-01,
       4.94125361e-01, 4.51278808e-01, 2.88420079e-01, 2.22519235e-01,
       2.12858211e-01, 1.32743817e-02, 1.51543915e-02, 1.96679574e-02,
       2.52482696e-02, 3.02907753e-02, 3.95858805e-02, 4.58665218e-02,
       5.63578935e-02, 6.63332928e-02, 7.50807576e-02, 8.04996240e-02,
       8.57307368e-02, 1.77463947e-01, 1.73933890e-01, 1.64444330e-01,
       1.59555319e-01, 1.05519447e-01, 1.48121923e-01, 1.21999462e-01,
       1.34312632e-01, 1.32121560e-01])

In [56]:
m[0]


array([ 22.59426302, -16.40784167,   9.09108748,   4.78558444,
         2.45894102,   1.6995729 ,   1.09476065,   1.00578351,
         0.82910545,   0.68787638,   0.06032004,   0.06685896,
         0.10185353,   0.10884695,   0.12068707,   0.14700897,
         0.59516538,   0.20996981,   0.23977529,   0.25156531,
         0.32137748,   0.52405156,   0.50318445,   0.36743366,
         0.45929487,   0.44519922,   0.43178955,   0.41751131,
         0.39918287,   0.38173515])

In [48]:
m[1][2]

array([-0.19693636, -0.07473161,  0.08123126, -0.1639276 ,  0.18648823,
        0.04005492, -0.18775482,  0.05059254, -0.04617048, -0.12816629,
       -0.47697179, -0.1632065 ,  0.32541249, -0.44381381,  0.17667252,
        0.12261167, -0.11883331,  0.02840793, -0.09024128,  0.1878645 ,
       -0.01378625,  0.2098644 , -0.02046525, -0.06384266, -0.10916391,
        0.05257043, -0.05336295, -0.2950068 ,  0.10340975,  0.06177241])