Análisis de componentes principales

In [1]:
import pandas as pd
import numpy as np


In [2]:
base = pd.read_csv(".\\AumentadaPFLD.csv")  #leer la base

In [6]:
matriz = base.to_numpy()

In [8]:
Matriz_covarianza = np.cov(matriz)
Matriz_covarianza

array([[141.92643678,  99.65517241,  78.89655172, ...,   6.04137931,
          1.35862069,  16.1862069 ],
       [ 99.65517241, 107.5862069 ,  60.79310345, ...,  -1.17241379,
          8.79310345,  10.62068966],
       [ 78.89655172,  60.79310345, 108.67241379, ...,  19.01724138,
         -4.51724138,  17.03448276],
       ...,
       [  6.04137931,  -1.17241379,  19.01724138, ...,  92.64482759,
         50.49655172,  53.6       ],
       [  1.35862069,   8.79310345,  -4.51724138, ...,  50.49655172,
         60.30344828,  43.57931034],
       [ 16.1862069 ,  10.62068966,  17.03448276, ...,  53.6       ,
         43.57931034,  92.92413793]])

In [9]:
from scipy import stats
matriz_estandarizada = stats.zscore(matriz, axis=1)


In [10]:
Matriz_correlacion = np.cov(matriz_estandarizada)
Matriz_correlacion

array([[ 1.03448276,  0.83428254,  0.65718853, ...,  0.05450259,
         0.01519213,  0.145805  ],
       [ 0.83428254,  1.03448276,  0.58162038, ..., -0.01214829,
         0.11293175,  0.10988373],
       [ 0.65718853,  0.58162038,  1.03448276, ...,  0.19606521,
        -0.05772525,  0.17535909],
       ...,
       [ 0.05450259, -0.01214829,  0.19606521, ...,  1.03448276,
         0.69888113,  0.59760358],
       [ 0.01519213,  0.11293175, -0.05772525, ...,  0.69888113,
         1.03448276,  0.60223815],
       [ 0.145805  ,  0.10988373,  0.17535909, ...,  0.59760358,
         0.60223815,  1.03448276]])

In [13]:
import numpy as np
from numpy.linalg import eig

In [15]:
v = eig(Matriz_covarianza)

In [19]:
v[0]

array([1.41899632e-311+1.41915853e-311j, 3.00000000e+001+3.00000000e+001j,
       3.00000000e+001+3.00000000e+001j, ...,
       0.00000000e+000+0.00000000e+000j, 0.00000000e+000+0.00000000e+000j,
       0.00000000e+000+0.00000000e+000j])